### PR TITLE
include ember-data custom transforms in namespace

### PR DESCRIPTION
**Pull request by koriroys**
allow models to have custom DS.attr transforms

### CODE REVIEW

**Comment by tricknotes** [comment]
Thanks @koriroys 
It seems good :+1: 

Could you update test against this behavior?
https://github.com/emberjs/ember-rails/blob/master/test/es6_modeul_test.rb#L5

**Comment by tricknotes** [comment]
There is a falling test [here](https://travis-ci.org/emberjs/ember-rails/builds/113366142).
> Error: test_transforms_type_module_should_be_registered_with_module_prefix(Es6ModuleTest): > ActionController::RoutingError: No route matches [GET] "/assets/transforms/user.js"

To fix this test, could you add the following file?
`test/dummy/app/assets/javascripts/transforms/user.module.es6`
``` js
import DS from 'ember-data';

export default DS.Transform.extend({

});
```

**Comment by koriroys** [comment]
Yeah sorry. I just did it real quick on github, thought it would be less involved. :smile_cat: good thing your tests catch it though.

**Comment by tricknotes** [comment]
All tests are passed :green_heart: 
Thanks for your nice fix @koriroys :rocket:

**Comment by koriroys** [comment]
No problemo. Thanks for the sweet gem.

**Pull request merged**
