### PR TITLE
Remove duplicate information from the README.

### PR DESCRIPTION
**Pull request by juankiz**

### CODE REVIEW

**Comment by tricknotes** [comment]
It works for me.

For example:
```
$ rails g ember:bootstrap --ember-path path/to/app

**Comment by tricknotes** [comment]
@juankiz 
Are there any case it doesn't work?

**Comment by juankiz** [comment]
@tricknotes I'm sorry I wasn't very clear. That paragraph is written twice in the README, so I removed the duplicate, but the functionality is working fine :)

**Comment by tricknotes** [comment]
Ah right.
Thanks man :smile:

**Pull request merged**
