### PR TITLE
add support for the active-model-adapter as a gem

### PR DESCRIPTION
**Pull request by fivetanley**
If this passes travis it should be fine to merge now.

### CODE REVIEW

**Comment by fivetanley** [comment]
@tricknotes I'm not sure how to fix the appraisals file here. Bundler gets conflicting stuff. :(

**Comment by tricknotes** [comment]
Confirmed :+1: 

We may drop old ember-data-source support in the next version of ember-rails.
It seems active-model-adapter-source is required by ember-source `>= 1.13`.
Right?

**Comment by tricknotes** [comment]
> We may drop old ember-data-source support in the next version of ember-rails.

This means that only ember-source `>= 1.8` will be supported.

**Comment by fivetanley** [comment]
> This means that only ember-source >= 1.8 will be supported.

That's fine. Ember Data has supported this version requirement for a few months.

**Comment by fivetanley** [comment]
@tricknotes how do we move this forward?

**Comment by tricknotes** [comment]
Sorry to my late, @fivetanley .
I should bump a new version which is supported only latest Ember & ember-data with this PR.

I'll be back in this weekend.

**Comment by tricknotes** [comment]
The old ember support was dropped by https://github.com/emberjs/ember-rails/pull/484.
It is ready to merge this PR.

@fivetanley 
Could you rebase to pass test?

**Comment by tricknotes** [comment]
Thanks @fivetanley .
I cherry picked this commit as 7fd2bb6e0fa6461a9ddea1520d843d95c518e471.

After travis feels happy, I'll release a new version.

**Pull request closed without merging**
